import type {
  Client,
  Cto,
  NetworkEvent,
  NocMetrics,
  Olt,
  Pon,
  Pop,
  Ticket,
} from '@/shared/types/network'

/** Centro aproximado — ajustar com área real da R20 depois */
const BASE = { lat: -23.5505, lng: -46.6333 }

export const seedPops: Omit<Pop, 'id'>[] = [
  {
    name: 'POP Centro',
    address: 'Av. Central, 100 — Centro',
    lat: BASE.lat,
    lng: BASE.lng,
    status: 'online',
    createdAt: new Date().toISOString(),
  },
  {
    name: 'POP Norte',
    address: 'Rua das Fibras, 45 — Zona Norte',
    lat: BASE.lat + 0.035,
    lng: BASE.lng - 0.02,
    status: 'online',
    createdAt: new Date().toISOString(),
  },
]

export const seedOlts: Array<Omit<Olt, 'id' | 'popId'> & { popIndex: number }> = [
  {
    popIndex: 0,
    name: 'OLT-ZTE-01',
    vendor: 'ZTE',
    ip: '10.10.1.2',
    status: 'online',
    lat: BASE.lat + 0.002,
    lng: BASE.lng + 0.001,
    createdAt: new Date().toISOString(),
  },
  {
    popIndex: 0,
    name: 'OLT-HW-02',
    vendor: 'Huawei',
    ip: '10.10.1.3',
    status: 'online',
    lat: BASE.lat - 0.004,
    lng: BASE.lng + 0.006,
    createdAt: new Date().toISOString(),
  },
  {
    popIndex: 1,
    name: 'OLT-FH-03',
    vendor: 'Fiberhome',
    ip: '10.10.2.2',
    status: 'alert',
    lat: BASE.lat + 0.038,
    lng: BASE.lng - 0.018,
    createdAt: new Date().toISOString(),
  },
]

export const seedPons: Array<Omit<Pon, 'id' | 'oltId'> & { oltIndex: number }> = [
  { oltIndex: 0, name: 'PON-0/1/1', port: 1, status: 'online', createdAt: new Date().toISOString() },
  { oltIndex: 0, name: 'PON-0/1/2', port: 2, status: 'online', createdAt: new Date().toISOString() },
  { oltIndex: 1, name: 'PON-0/1/1', port: 1, status: 'online', createdAt: new Date().toISOString() },
  { oltIndex: 1, name: 'PON-0/1/2', port: 2, status: 'alert', createdAt: new Date().toISOString() },
  { oltIndex: 2, name: 'PON-0/1/1', port: 1, status: 'online', createdAt: new Date().toISOString() },
  { oltIndex: 2, name: 'PON-0/1/2', port: 2, status: 'offline', createdAt: new Date().toISOString() },
]

export const seedCtos: Array<
  Omit<Cto, 'id' | 'oltId' | 'ponId'> & { oltIndex: number; ponIndex: number }
> = [
  {
    oltIndex: 0,
    ponIndex: 0,
    name: 'CTO-CENTRO-01',
    code: 'CTO-001',
    capacity: 16,
    occupiedPorts: 11,
    freePorts: 5,
    splitter: '1:16',
    distanceMeters: 420,
    status: 'online',
    lat: BASE.lat + 0.008,
    lng: BASE.lng + 0.004,
    occupancyPercent: 69,
    createdAt: new Date().toISOString(),
  },
  {
    oltIndex: 0,
    ponIndex: 1,
    name: 'CTO-CENTRO-02',
    code: 'CTO-002',
    capacity: 8,
    occupiedPorts: 7,
    freePorts: 1,
    splitter: '1:8',
    distanceMeters: 610,
    status: 'alert',
    lat: BASE.lat + 0.012,
    lng: BASE.lng - 0.003,
    occupancyPercent: 88,
    createdAt: new Date().toISOString(),
  },
  {
    oltIndex: 1,
    ponIndex: 2,
    name: 'CTO-SUL-01',
    code: 'CTO-003',
    capacity: 16,
    occupiedPorts: 6,
    freePorts: 10,
    splitter: '1:16',
    distanceMeters: 890,
    status: 'online',
    lat: BASE.lat - 0.01,
    lng: BASE.lng + 0.012,
    occupancyPercent: 38,
    createdAt: new Date().toISOString(),
  },
  {
    oltIndex: 2,
    ponIndex: 4,
    name: 'CTO-NORTE-01',
    code: 'CTO-004',
    capacity: 16,
    occupiedPorts: 14,
    freePorts: 2,
    splitter: '1:16',
    distanceMeters: 1100,
    status: 'alert',
    lat: BASE.lat + 0.042,
    lng: BASE.lng - 0.01,
    occupancyPercent: 88,
    createdAt: new Date().toISOString(),
  },
]

export const seedClients: Array<
  Omit<Client, 'id' | 'ctoId' | 'oltId' | 'ponId'> & { ctoIndex: number }
> = [
  {
    ctoIndex: 0,
    name: 'João Silva',
    plan: '500 Mega',
    onuModel: 'ZTE F670L',
    powerDbm: -22.4,
    lastAccessAt: new Date().toISOString(),
    ip: '100.64.10.21',
    equipment: 'ONU Bridge',
    mac: 'AA:BB:CC:11:22:01',
    serial: 'ZTEG12345001',
    status: 'online',
    lat: BASE.lat + 0.0082,
    lng: BASE.lng + 0.0042,
    createdAt: new Date().toISOString(),
  },
  {
    ctoIndex: 0,
    name: 'Maria Souza',
    plan: '300 Mega',
    onuModel: 'Huawei EG8145',
    powerDbm: -27.1,
    lastAccessAt: new Date(Date.now() - 3600_000).toISOString(),
    ip: '100.64.10.22',
    equipment: 'ONU Router',
    mac: 'AA:BB:CC:11:22:02',
    serial: 'HWTC12345002',
    status: 'alert',
    lat: BASE.lat + 0.0085,
    lng: BASE.lng + 0.0035,
    createdAt: new Date().toISOString(),
  },
  {
    ctoIndex: 1,
    name: 'Pedro Oliveira',
    plan: '700 Mega',
    onuModel: 'ZTE F670L',
    powerDbm: -18.0,
    lastAccessAt: new Date(Date.now() - 86_400_000).toISOString(),
    ip: '100.64.10.31',
    equipment: 'ONU Bridge',
    mac: 'AA:BB:CC:11:22:03',
    serial: 'ZTEG12345003',
    status: 'offline',
    lat: BASE.lat + 0.0123,
    lng: BASE.lng - 0.0028,
    createdAt: new Date().toISOString(),
  },
  {
    ctoIndex: 2,
    name: 'Ana Costa',
    plan: '200 Mega',
    onuModel: 'Fiberhome AN5506',
    powerDbm: -23.8,
    lastAccessAt: new Date().toISOString(),
    ip: '100.64.20.11',
    equipment: 'ONU Router',
    mac: 'AA:BB:CC:11:22:04',
    serial: 'FHTT12345004',
    status: 'online',
    lat: BASE.lat - 0.0102,
    lng: BASE.lng + 0.0124,
    createdAt: new Date().toISOString(),
  },
  {
    ctoIndex: 3,
    name: 'Carlos Mendes',
    plan: '500 Mega',
    onuModel: 'ZTE F670L',
    powerDbm: -29.2,
    lastAccessAt: new Date(Date.now() - 7200_000).toISOString(),
    ip: '100.64.30.15',
    equipment: 'ONU Bridge',
    mac: 'AA:BB:CC:11:22:05',
    serial: 'ZTEG12345005',
    status: 'alert',
    lat: BASE.lat + 0.0425,
    lng: BASE.lng - 0.0095,
    createdAt: new Date().toISOString(),
  },
]

export const seedEvents: Omit<NetworkEvent, 'id'>[] = [
  {
    type: 'client_offline',
    severity: 'critical',
    title: 'Cliente Offline',
    description: 'Pedro Oliveira sem sessão há mais de 1h',
    assetType: 'client',
    assetId: 'pending',
    assetName: 'Pedro Oliveira',
    createdAt: new Date(Date.now() - 1_800_000).toISOString(),
    acknowledged: false,
  },
  {
    type: 'power_alert',
    severity: 'warning',
    title: 'Alerta de potência',
    description: 'Sinal abaixo de -26 dBm',
    assetType: 'client',
    assetId: 'pending',
    assetName: 'Maria Souza',
    createdAt: new Date(Date.now() - 900_000).toISOString(),
    acknowledged: false,
  },
  {
    type: 'signal_oscillation',
    severity: 'warning',
    title: 'Oscilação de sinal',
    description: 'Variação detectada na CTO-NORTE-01',
    assetType: 'cto',
    assetId: 'pending',
    assetName: 'CTO-NORTE-01',
    createdAt: new Date(Date.now() - 600_000).toISOString(),
    acknowledged: false,
  },
]

export const seedTickets: Omit<Ticket, 'id'>[] = [
  {
    title: 'Cliente sem conexão — Pedro Oliveira',
    status: 'open',
    priority: 'high',
    createdAt: new Date().toISOString(),
  },
  {
    title: 'Sinal ruim — Maria Souza',
    status: 'in_progress',
    priority: 'medium',
    createdAt: new Date().toISOString(),
  },
]

export const seedMetrics: NocMetrics = {
  clientsOnline: 1240,
  clientsOffline: 37,
  clientsBadSignal: 12,
  oltsCount: 3,
  ticketsOpen: 18,
  networkAvailabilityPercent: 99.4,
  updatedAt: new Date().toISOString(),
}
